// CampusPilot AI - Comprehensive Opportunities Data Repository with Diverse Real-World Stipends (₹5,000 - ₹1,60,000+)

const INITIAL_OPPORTUNITIES = [
  // --- TIER 1: EARLY STAGE & STARTUP INTERNSHIPS (₹5,000 - ₹12,000 / month) ---
  {
    id: "opp-5k-1",
    title: "Junior Python & Web Automation Intern",
    company: "EduVibe EdTech",
    logo: "🌱",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 5000,
    stipend: "₹5,000 / month",
    location: "Remote",
    requiredSkills: ["Python", "HTML", "Automation", "SQL"],
    degreeEligible: ["B.Tech", "BCA", "B.Sc CS", "All Degrees"],
    targetYears: ["Year 1", "Year 2", "Year 3", "Year 4"],
    branches: ["All Branches"],
    minGpa: 6.5,
    deadlineDays: 14,
    postedDate: "2026-08-16",
    applyUrl: "https://eduvibe.io/careers",
    description: "Write Python automation scripts for educational data processing, test portal workflows, and build basic web scraping pipelines.",
    isHotAlert: false,
    supportedAutoApply: true,
    applicationQuestions: [
      "Describe a Python script or small automation project you created.",
      "How many hours per week can you contribute to remote development?"
    ]
  },
  {
    id: "opp-7k-1",
    title: "Junior React & Frontend Developer Intern",
    company: "TechSprout Studios",
    logo: "🎨",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 7500,
    stipend: "₹7,500 / month",
    location: "Remote / Pune",
    requiredSkills: ["JavaScript", "React", "CSS", "UI/UX Design"],
    degreeEligible: ["B.Tech", "BCA", "All Degrees"],
    targetYears: ["Year 1", "Year 2", "Year 3", "Year 4"],
    branches: ["Computer Science", "IT", "All Branches"],
    minGpa: 6.5,
    deadlineDays: 12,
    postedDate: "2026-08-15",
    applyUrl: "https://techsprout.dev/jobs",
    description: "Assist design and engineering leads in building responsive UI components in React, styling responsive landing pages with CSS, and debugging frontend UI.",
    isHotAlert: false,
    supportedAutoApply: true,
    applicationQuestions: [
      "Share a link to your GitHub or interactive frontend portfolio.",
      "What is your experience with React state management and responsive design?"
    ]
  },
  {
    id: "opp-8k-1",
    title: "Junior Data Analytics & BI Intern",
    company: "NexaLab Analytics",
    logo: "📊",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 8000,
    stipend: "₹8,000 / month",
    location: "Remote / Hyderabad",
    requiredSkills: ["Python", "SQL", "Excel", "Tableau"],
    degreeEligible: ["B.Tech", "B.Sc", "BCA", "All Degrees"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["All Engineering & Science Branches"],
    minGpa: 7.0,
    deadlineDays: 10,
    postedDate: "2026-08-14",
    applyUrl: "https://nexalab.ai/careers",
    description: "Extract business insights from SQL databases, create visual Tableau dashboards, and clean customer behavioral datasets using Python Pandas.",
    isHotAlert: false,
    supportedAutoApply: true,
    applicationQuestions: [
      "Describe a data visualization or analytical report you generated using SQL or Python.",
      "How do you handle missing values and outliers in raw datasets?"
    ]
  },
  {
    id: "opp-10k-1",
    title: "Python Scripting & Backend Intern",
    company: "CodeCraft Labs",
    logo: "⚙️",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 10000,
    stipend: "₹10,000 / month",
    location: "Remote / Bengaluru",
    requiredSkills: ["Python", "FastAPI", "SQL", "Git"],
    degreeEligible: ["B.Tech", "MCA", "BCA"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["Computer Science", "IT", "ECE"],
    minGpa: 7.0,
    deadlineDays: 9,
    postedDate: "2026-08-13",
    applyUrl: "https://codecraftlabs.com/join",
    description: "Build lightweight FastAPI endpoints, maintain SQLite/PostgreSQL schemas, and write unit tests for internal SaaS tools.",
    isHotAlert: false,
    supportedAutoApply: true,
    applicationQuestions: [
      "Explain how RESTful APIs exchange data between client and server.",
      "Provide your GitHub profile with Python code examples."
    ]
  },
  {
    id: "opp-12k-1",
    title: "Junior Data Annotation & ML Pipeline Intern",
    company: "DataMinds AI",
    logo: "🤖",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 12000,
    stipend: "₹12,000 / month",
    location: "Remote",
    requiredSkills: ["Python", "Pandas", "Machine Learning", "Git"],
    degreeEligible: ["B.Tech", "B.Sc CS", "All Degrees"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["Computer Science", "AI/DS", "ECE"],
    minGpa: 7.0,
    deadlineDays: 11,
    postedDate: "2026-08-12",
    applyUrl: "https://dataminds.ai/careers",
    description: "Curate high-quality NLP datasets, validate ML ground truth annotations, and assist lead researchers in running PyTorch evaluation benchmarks.",
    isHotAlert: false,
    supportedAutoApply: true,
    applicationQuestions: [
      "What machine learning algorithms have you implemented from scratch or with scikit-learn?",
      "Why is clean data preprocessing critical for AI model accuracy?"
    ]
  },

  // --- TIER 2: GROWTH STARTUPS & MID-TIER INTERNSHIPS (₹15,000 - ₹30,000 / month) ---
  {
    id: "opp-15k-1",
    title: "Frontend Web Developer Intern",
    company: "Groww Labs",
    logo: "📈",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 15000,
    stipend: "₹15,000 / month",
    location: "Bengaluru / Remote",
    requiredSkills: ["JavaScript", "React", "TypeScript", "Tailwind"],
    degreeEligible: ["B.Tech", "BCA", "MCA"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["Computer Science", "IT", "ECE"],
    minGpa: 7.2,
    deadlineDays: 8,
    postedDate: "2026-08-11",
    applyUrl: "https://groww.in/careers",
    description: "Develop high-performance financial charts and user dashboards using React, TypeScript, and responsive Tailwind CSS.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "What React hooks do you use most often and why?",
      "Share your experience building responsive interactive web apps."
    ]
  },
  {
    id: "opp-20k-1",
    title: "Operations Tech & Logistics Intern",
    company: "Swiggy Launchpad",
    logo: "🛵",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 20000,
    stipend: "₹20,000 / month",
    location: "Bengaluru / Hybrid",
    requiredSkills: ["Python", "SQL", "Data Structures", "APIs"],
    degreeEligible: ["B.Tech", "Dual Degree"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["All Engineering Branches"],
    minGpa: 7.2,
    deadlineDays: 7,
    postedDate: "2026-08-10",
    applyUrl: "https://careers.swiggy.com",
    description: "Analyze delivery partner dispatch metrics, optimize geospatial microservice queries, and automate incident reporting dashboards.",
    isHotAlert: false,
    supportedAutoApply: true,
    applicationQuestions: [
      "How do you approach querying and aggregating large SQL datasets?",
      "Describe a data structure you used to solve an algorithmic problem."
    ]
  },
  {
    id: "opp-25k-1",
    title: "Full Stack React Developer & UI Intern",
    company: "Campus Tech Labs",
    logo: "🎓",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 25000,
    stipend: "₹25,000 / month",
    location: "Remote / Hyderabad",
    requiredSkills: ["JavaScript", "React", "Node.js", "SQL", "UI/UX Design"],
    degreeEligible: ["B.Tech", "BCA", "B.Sc CS"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["All Engineering & CS Branches"],
    minGpa: 7.0,
    deadlineDays: 9,
    postedDate: "2026-08-09",
    applyUrl: "https://campustechlabs.io/careers",
    description: "Build clean, responsive web application features using modern HTML, CSS glassmorphism components, and JavaScript state engines.",
    isHotAlert: false,
    supportedAutoApply: true,
    applicationQuestions: [
      "Provide links to your web portfolio or GitHub repositories showcasing your UI skills.",
      "How do you ensure clean CSS and responsive performance across mobile and desktop?"
    ]
  },
  {
    id: "opp-30k-1",
    title: "Backend Microservices & API Intern",
    company: "Zepto Tech",
    logo: "⚡",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 30000,
    stipend: "₹30,000 / month",
    location: "Mumbai / Remote",
    requiredSkills: ["Node.js", "Python", "PostgreSQL", "Redis", "REST APIs"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["Computer Science", "IT"],
    minGpa: 7.5,
    deadlineDays: 6,
    postedDate: "2026-08-08",
    applyUrl: "https://zeptonow.com/careers",
    description: "Design low-latency cart inventory microservices, Redis caching layers, and high-concurrency order placement pipelines.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "How does Redis caching improve database throughput under heavy load?",
      "Describe an API endpoint you designed and optimized."
    ]
  },

  // --- TIER 3: ESTABLISHED TECH UNICORNS (₹45,000 - ₹65,000 / month) ---
  {
    id: "opp-45k-1",
    title: "API Developer Experience & Tools Intern",
    company: "Postman",
    logo: "📮",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 45000,
    stipend: "₹45,000 / month",
    location: "Bengaluru / Remote",
    requiredSkills: ["TypeScript", "Node.js", "REST APIs", "Git"],
    degreeEligible: ["B.Tech", "Dual Degree"],
    targetYears: ["Year 3", "Year 4"],
    branches: ["Computer Science", "IT"],
    minGpa: 7.5,
    deadlineDays: 10,
    postedDate: "2026-08-07",
    applyUrl: "https://postman.com/careers",
    description: "Build developer workflow tooling, API schema validation suites, and CLI integrations used by 30M+ developers worldwide.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "What are the best practices for designing public REST APIs?",
      "Describe a TypeScript or Node.js project you authored."
    ]
  },
  {
    id: "opp-50k-1",
    title: "Payments Platform & Core Systems Intern",
    company: "Razorpay",
    logo: "💳",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 50000,
    stipend: "₹50,000 / month",
    location: "Bengaluru",
    requiredSkills: ["Java", "Go", "Python", "Distributed Systems", "SQL"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 3", "Year 4"],
    branches: ["Computer Science", "ECE", "IT"],
    minGpa: 7.8,
    deadlineDays: 8,
    postedDate: "2026-08-06",
    applyUrl: "https://razorpay.com/jobs",
    description: "Work on mission-critical payment gateway routing, webhook retry engines, and zero-downtime financial ledger databases.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "Explain the ACID properties of relational databases with an example.",
      "How do you ensure idempotency in asynchronous webhooks?"
    ]
  },
  {
    id: "opp-65k-1",
    title: "High-Concurrency Backend & Trust Systems Intern",
    company: "CRED",
    logo: "💎",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 65000,
    stipend: "₹65,000 / month",
    location: "Bengaluru",
    requiredSkills: ["Go", "Java", "Kafka", "Data Structures", "PostgreSQL"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 3", "Year 4"],
    branches: ["Computer Science", "IT"],
    minGpa: 8.0,
    deadlineDays: 7,
    postedDate: "2026-08-05",
    applyUrl: "https://cred.club/careers",
    description: "Scale high-throughput event streaming pipelines using Apache Kafka, write ultra-fast Go microservices, and ensure sub-10ms user authentication.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "Describe an event-driven architecture using Kafka or message queues.",
      "What is your approach to handling database concurrency lock contention?"
    ]
  },

  // --- TIER 4: GLOBAL ENTERPRISE LEADERS (₹80,000 - ₹95,000 / month) ---
  {
    id: "opp-80k-1",
    title: "Distributed Catalog & Search Intern",
    company: "Flipkart",
    logo: "🛍️",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 80000,
    stipend: "₹80,000 / month",
    location: "Bengaluru",
    requiredSkills: ["Java", "Python", "Data Structures", "Algorithms", "Elasticsearch"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 3", "Year 4"],
    branches: ["Computer Science", "IT", "ECE"],
    minGpa: 7.8,
    deadlineDays: 9,
    postedDate: "2026-08-04",
    applyUrl: "https://flipkartcareers.com",
    description: "Develop sub-50ms search query rankers, inverted index optimizations, and real-time inventory caching across millions of product SKUs.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "How would you design an autocomplete search engine for high-traffic e-commerce?",
      "Share an algorithm optimization that significantly reduced time complexity."
    ]
  },
  {
    id: "opp-90k-1",
    title: "Silicon Edge AI & Compiler Optimization Intern",
    company: "Intel",
    logo: "🔷",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 90000,
    stipend: "₹90,000 / month",
    location: "Bengaluru",
    requiredSkills: ["C++", "Python", "Compilers", "CUDA", "LLVM"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 3", "Year 4"],
    branches: ["Computer Science", "ECE", "AI/ML"],
    minGpa: 8.0,
    deadlineDays: 11,
    postedDate: "2026-08-03",
    applyUrl: "https://jobs.intel.com",
    description: "Optimize OpenVINO deep learning inference kernels for Intel silicon, integrate LLVM tensor transformations, and benchmark NPU runtime power efficiency.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "Detail your experience with low-level C/C++ memory management and compiler optimizations.",
      "How do hardware vector extensions (AVX/NEON) accelerate neural network inference?"
    ]
  },
  {
    id: "opp-95k-1",
    title: "Zero-Trust Cloud Security & Telemetry Intern",
    company: "Cisco",
    logo: "🌐",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 95000,
    stipend: "₹95,000 / month",
    location: "Bengaluru",
    requiredSkills: ["Python", "Go", "Networking", "Kubernetes", "Security"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 3", "Year 4"],
    branches: ["Computer Science", "IT", "ECE"],
    minGpa: 7.8,
    deadlineDays: 10,
    postedDate: "2026-08-02",
    applyUrl: "https://jobs.cisco.com",
    description: "Build automated threat detection probes, eBPF network telemetry collectors, and identity-aware proxy services for cloud environments.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "Explain the fundamental concepts of Zero-Trust security and TLS encryption.",
      "Describe your hands-on experience with Linux networking and containerization."
    ]
  },

  // --- TIER 5: FAANG & FRONTIER AI RESEARCH LABS (₹1,10,000 - ₹1,60,000 / month) ---
  {
    id: "opp-110k-1",
    title: "Creative Cloud Firefly Generative AI Intern",
    company: "Adobe",
    logo: "🅰️",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 110000,
    stipend: "₹1,10,000 / month",
    location: "Noida / Bengaluru",
    requiredSkills: ["C++", "JavaScript", "WebGL", "Machine Learning", "React"],
    degreeEligible: ["B.Tech", "Dual Degree"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["Computer Science", "Design Tech", "IT"],
    minGpa: 7.5,
    deadlineDays: 11,
    postedDate: "2026-08-01",
    applyUrl: "https://adobe.com/careers",
    description: "Build interactive canvas tooling powered by Firefly generative models, GPU web shaders, and dynamic vector manipulation.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "Describe a project blending generative AI with interactive frontend experiences.",
      "How do WebGL or GPU shaders optimize browser rendering performance?"
    ]
  },
  {
    id: "opp-115k-1",
    title: "AWS Cloud & Microservices Engineering Intern",
    company: "Amazon",
    logo: "📦",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 115000,
    stipend: "₹1,15,000 / month",
    location: "Hyderabad / Bengaluru",
    requiredSkills: ["Java", "Python", "SQL", "AWS", "Data Structures"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 3", "Year 4"],
    branches: ["Computer Science", "IT", "ECE"],
    minGpa: 7.5,
    deadlineDays: 5,
    postedDate: "2026-08-01",
    applyUrl: "https://amazon.jobs",
    description: "Work on Amazon e-commerce backend microservices, high-concurrency order processing pipelines, and AWS cloud tools.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "Which Amazon Leadership Principle resonates most with your past project experience?",
      "Describe a complex data structure problem you solved recently."
    ]
  },
  {
    id: "opp-125k-1",
    title: "Azure Cloud Distributed Systems Intern",
    company: "Microsoft",
    logo: "🪟",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 125000,
    stipend: "₹1,25,000 / month",
    location: "Bengaluru / Noida",
    requiredSkills: ["C++", "C#", "Python", "Data Structures", "SQL"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["All Engineering Branches"],
    minGpa: 7.8,
    deadlineDays: 6,
    postedDate: "2026-08-01",
    applyUrl: "https://careers.microsoft.com",
    description: "Work on Azure Cloud analytics, Copilot telemetry models, and large-scale distributed enterprise data systems.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "What experience do you have with data modeling in Python / C#?",
      "How do you approach optimizing algorithm performance and SQL queries?"
    ]
  },
  {
    id: "opp-130k-1",
    title: "iOS Neural Engine Low-Level Systems Intern",
    company: "Apple",
    logo: "🍎",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 130000,
    stipend: "₹1,30,000 / month",
    location: "Bengaluru / Hyderabad",
    requiredSkills: ["C++", "Swift", "Python", "Data Structures", "Metal"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["Computer Science", "ECE", "IT"],
    minGpa: 7.8,
    deadlineDays: 14,
    postedDate: "2026-08-01",
    applyUrl: "https://apple.com/careers",
    description: "Optimize on-device CoreML neural execution, silicon acceleration pipelines, and energy-efficient inference kernels.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "Describe low-level memory optimizations you have applied in C/C++ or Swift.",
      "How do hardware architectures influence deep learning runtime efficiency?"
    ]
  },
  {
    id: "opp-135k-1",
    title: "CUDA Kernel Acceleration & Deep Learning Intern",
    company: "NVIDIA",
    logo: "👁️",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 135000,
    stipend: "₹1,35,000 / month",
    location: "Bengaluru / Hybrid",
    requiredSkills: ["C++", "CUDA", "PyTorch", "Python"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 3", "Year 4"],
    branches: ["Computer Science", "AI/ML", "ECE"],
    minGpa: 8.0,
    deadlineDays: 11,
    postedDate: "2026-08-01",
    applyUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
    description: "Build high-throughput GPU kernels, LLM inference acceleration engines, and CUDA memory management tools.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "Explain your familiarity with GPU parallel architecture or C++ memory management.",
      "Share a repository or project where you benchmarked deep learning models."
    ]
  },
  {
    id: "opp-140k-1",
    title: "Multimodal Gemini & Edge ML Research Intern",
    company: "Google DeepMind",
    logo: "🌐",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 140000,
    stipend: "₹1,40,000 / month",
    location: "Bengaluru",
    requiredSkills: ["Python", "PyTorch", "Transformers", "SQL", "Machine Learning"],
    degreeEligible: ["B.Tech", "M.Tech", "Dual Degree"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["Computer Science", "AI/DS", "ECE", "IT"],
    minGpa: 8.0,
    deadlineDays: 8,
    postedDate: "2026-08-01",
    applyUrl: "https://careers.google.com",
    description: "Join Google Research & Engineering teams building next-generation Multimodal AI models, Gemini API infrastructure, and low-latency Edge ML solutions.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "Why are you passionate about building AI & ML systems at Google?",
      "Briefly describe a technical project where you implemented data structures or Machine Learning."
    ]
  },
  {
    id: "opp-150k-1",
    title: "Claude AI Interpretability & Alignment Fellow",
    company: "Anthropic",
    logo: "🛡️",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 150000,
    stipend: "₹1,50,000 / month",
    location: "Remote",
    requiredSkills: ["Python", "PyTorch", "Transformers", "Mechanistic Interpretability"],
    degreeEligible: ["B.Tech", "M.Tech", "Dual Degree"],
    targetYears: ["Year 3", "Year 4"],
    branches: ["Computer Science", "Cognitive Science", "Physics"],
    minGpa: 8.2,
    deadlineDays: 13,
    postedDate: "2026-08-01",
    applyUrl: "https://anthropic.com/careers",
    description: "Investigate dictionary learning on transformer representations, automated circuit discovery, and Constitutional AI alignment guarantees.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "What is your approach to analyzing neural activation patterns or induction heads?",
      "Why is constitutional AI governance essential for safe deployment?"
    ]
  },
  {
    id: "opp-160k-1",
    title: "Frontier AI Safety & Alignment Research Intern",
    company: "OpenAI",
    logo: "🤖",
    category: "Internships",
    internshipType: "paid",
    stipendAmount: 160000,
    stipend: "₹1,60,000 / month",
    location: "Remote / Hybrid",
    requiredSkills: ["Python", "PyTorch", "Transformers", "RLHF", "Machine Learning"],
    degreeEligible: ["B.Tech", "M.Tech", "Dual Degree"],
    targetYears: ["Year 3", "Year 4"],
    branches: ["Computer Science", "AI/ML", "Mathematics"],
    minGpa: 8.5,
    deadlineDays: 15,
    postedDate: "2026-08-01",
    applyUrl: "https://openai.com/careers",
    description: "Research frontier LLM alignment, interpretability probes, and red-teaming safety evaluation suites.",
    isHotAlert: true,
    supportedAutoApply: true,
    applicationQuestions: [
      "What area of AI alignment or safety research do you find most critical today?",
      "Describe an experiment you designed to analyze model behavior or latent representations."
    ]
  },

  // --- TIER 6: UNPAID RESEARCH FELLOWSHIPS & NON-PROFIT LABS ---
  {
    id: "opp-unpaid-1",
    title: "Open Foundation Model & Dataset Fellowship",
    company: "Hugging Face / Open Source Collective",
    logo: "🤗",
    category: "Internships",
    internshipType: "unpaid",
    stipendAmount: 0,
    stipend: "Unpaid (Certificates, Mentorship & GPU Credits Provided)",
    location: "Remote",
    requiredSkills: ["Python", "PyTorch", "Transformers", "Git", "Machine Learning"],
    degreeEligible: ["All Degrees"],
    targetYears: ["Year 1", "Year 2", "Year 3", "Year 4"],
    branches: ["All Branches"],
    minGpa: 0,
    deadlineDays: 14,
    postedDate: "2026-08-01",
    applyUrl: "https://huggingface.co/join-us",
    description: "Collaborate with top open-source researchers to fine-tune open weights LLMs and contribute to public datasets.",
    isHotAlert: false,
    supportedAutoApply: true,
    applicationQuestions: [
      "What open-source projects or libraries have you used or contributed to?",
      "How will this mentorship help advance your research goals?"
    ]
  },
  {
    id: "opp-unpaid-2",
    title: "Multilingual Speech & Indic NLP Research Fellow",
    company: "Bharat AI Foundation",
    logo: "🔬",
    category: "Internships",
    internshipType: "unpaid",
    stipendAmount: 0,
    stipend: "Unpaid (Paper Co-Authorship & Recommendation Letter)",
    location: "Remote",
    requiredSkills: ["Python", "NLP", "Machine Learning", "LaTeX", "Data Analysis"],
    degreeEligible: ["B.Tech", "M.Tech"],
    targetYears: ["Year 2", "Year 3", "Year 4"],
    branches: ["Computer Science", "AI/ML"],
    minGpa: 7.5,
    deadlineDays: 18,
    postedDate: "2026-08-01",
    applyUrl: "https://bharatai.org/fellowships",
    description: "Assist lead scientists in processing Indian language speech datasets and writing research papers for IEEE/ACL conferences.",
    isHotAlert: false,
    supportedAutoApply: true,
    applicationQuestions: [
      "Have you authored or co-authored academic papers or technical reports before?",
      "Which NLP techniques or machine learning models are you most familiar with?"
    ]
  }
];

if (typeof window !== 'undefined') {
  window.CampusPilotData = window.CampusPilotData || {};
  window.CampusPilotData.INITIAL_OPPORTUNITIES = INITIAL_OPPORTUNITIES;
}
